---
title: "Stats 744/big data"
date: "`r format(Sys.time(), '%d %B %Y')`"
bibliography: bigdata.bib
output: github_document
---

(the `.md` version of this file is rendered from `README.Rmd`, please edit there)

A reading course ("special topics in statistics") at McMaster University, Fall 2025

Basic introduction to tools 

## References (in no particular order)

* "Big Book of R" section on [Data, Databases and Engineering](https://www.bigbookofr.com/chapters/data%20databases%20and%20engineering), especially [Enterprise Databases with R](https://smithjd.github.io/sql-pet/) [@smithexploring]
* ditto, [Big Data section](https://www.bigbookofr.com/chapters/big%20data)
* [CRAN high-performance computing task view](https://cran.r-project.org/web/views/HighPerformanceComputing.html)

## Topics (in no particular order)

* command line bullshittery (Docker etc.)
* Arrow/Parquet
* SQL and substitutes (e.g. `dbplyr`); also cf `data.table`
* benchmarking
* sharding
* map-reduce
* federated algorithms
* cloud platforms and tools: Azure, Spark, etc.
* parallel computing, different models (shared vs distributed memory etc)

## More links (again in no particular order)


* https://fastverse.github.io/fastverse/ <https://fastverse.github.io/fastverse/* https://hackmd.io/@dushoff/theobioSummerLearning#containers-Docker-etc
* Ross, Noam. 2013. “FasteR! HigheR! StrongeR! - A Guide to Speeding Up R Code for Busy People.” Noam Ross, April 25.  http://www.noamross.net/blog/2013/4/25/faster-talk.html <http://www.noamross.net/blog/2013/4/25/faster-talk.html.
* https://cran.r-project.org/web/views/HighPerformanceComputing.html
* https://missing.csail.mit.edu/2020/data-wrangling/
* https://github.com/bbolker/compstatsR

## Docker/adventureworks stuff

I think this works (in lieu of what is suggested in sections 4.4-4.7 of the Smith et al book)

In a shell (RStudio Terminal or a standalone terminal/shell window):

```bash
## set MYDIR to somewhere sensible on your system
## I think the only important thing is that this be a *writeable* directory
## export MYDIR=/home/bolker/Documents/classes/stat794_bigdata/sql-pet
export MYDIR=/tmp
## get/update postgres image
docker pull postgres
## clean up
docker rm --force adventureworks
## start up the container
docker run -e POSTGRES_PASSWORD="psql" --detach  --name adventureworks --publish 5432:5432 --mount type=bind,source="$MYDIR",target=/petdir postgres:11 
docker exec -i adventureworks psql -U postgres -c "CREATE DATABASE adventureworks;"
```

Then in R/RStudio:

```r
library(DBI)
con <- dbConnect(          # use in other settings
  RPostgres::Postgres(),
  # without the previous and next lines, some functions fail with bigint data 
  #   so change int64 to integer
  bigint = "integer",  
  host = "localhost",
  port = 5432,  # this version still using 5432!!!
  user = "postgres",
  password = "psql",
  dbname = "adventureworks"
)
print(con)
```

If this all worked you should see

```
<PqConnection> adventureworks@localhost:5432
```

## References
